# Applying values in a new column - this time having grouped by a column first

Import libraries, drive, df

Make a subset of the dataframe

Use Groupby - to summarise the data by a column

Applying an aggregate value to each value you have grouped by

Use loc() to create an if-else condition and apply to a new column

EXERCISE

Use loc() to create an if-else condition

Group by and check stats for those grouped values

Create a new column and define what goes in it

2nd version - Create a new column and define what goes in it

Reviewing NaN values

Renaming values

**Import libraries, drive, df**

In [ ]:
## -- Loading Libraries --
import pandas as pd
import numpy as np
import os

In [ ]:
#Importing google drive#

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Importing the whole df from drive#

df = pd.read_pickle('/content/drive/MyDrive/merged_frequency.pkl')

**Make a subset of the dataframe**

In [ ]:
#Making a subset of the df

df_subset = df[:1000000]

In [ ]:
#Checking what's in the df

df_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 19 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Unnamed: 0              1000000 non-null  int64
 1   product_id              1000000 non-null  int64
 2   product_name            1000000 non-null  object
 3   aisle_id                1000000 non-null  int64
 4   department_id           1000000 non-null  int64
 5   prices                  1000000 non-null  float64
 6   order_id                1000000 non-null  int64
 7   user_id                 1000000 non-null  int64
 8   eval_set                1000000 non-null  object
 9   order_number            1000000 non-null  int64
 10  order_dow               1000000 non-null  int64
 11  order_hour_of_day       1000000 non-null  int64
 12  days_since_prior_order  936078 non-null   float64
 13  add_to_cart_order       1000000 non-null  int64
 14  reordered               1000000 non-null  int64
 15  _merge                  1000000 non-null  category
 16  price_range_loc         1000000 non-null  object
 17  busiest_days            1000000 non-null  object
 18  busiest_time            1000000 non-null  object
dtypes: category(1), float64(2), int64(11), object(5)
memory usage: 138.3+ MB

In [ ]:
df.shape

(3240395, 19)

In [ ]:
df_subset.shape

(1000000, 19)

In [ ]:
df_subset.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_days,busiest_time
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,2907475,96682,prior,23,4,14,14.0,3,1,both,Mid-range product,Least busy days,Busiest time
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,3038506,39081,prior,16,2,17,30.0,5,0,both,Mid-range product,Regularly busy days,Regularly busy time
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,3185203,95847,prior,49,1,7,3.0,6,1,both,Mid-range product,Busiest days,Regularly busy time
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,1830804,14910,prior,56,4,12,6.0,3,1,both,Mid-range product,Least busy days,Regularly busy time
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Busiest days,Regularly busy time

**Use Groupby - to summarise the data by a column**

In [ ]:
#using groupby for the first time - no output by self

df.groupby('product_name')

In [ ]:
#Using groupby with an agg() (aggregate) function does produce a result

#here we goup by department first, and then show average for all of those.

#gives average orders per department

df_subset.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.352605
2                17.356119
3                17.484832
4                18.214165
5                15.017885
6                16.408631
7                17.131898
8                15.533981
9                15.839461
10               20.554965
11               16.644595
12               16.434299
13               16.411972
14               17.020195
15               16.488061
16               17.710705
17               16.119392
18               19.515857
19               16.950390
20               16.360832
21               23.434286

In [ ]:
#Does the samr thing,

df_subset.groupby('department_id')['order_number'].mean()

department_id
1     15.352605
2     17.356119
3     17.484832
4     18.214165
5     15.017885
6     16.408631
7     17.131898
8     15.533981
9     15.839461
10    20.554965
11    16.644595
12    16.434299
13    16.411972
14    17.020195
15    16.488061
16    17.710705
17    16.119392
18    19.515857
19    16.950390
20    16.360832
21    23.434286
Name: order_number, dtype: float64

In [ ]:
#Can do multiple aggregations at once

df_subset.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.352605   1  99
2                17.356119   1  99
3                17.484832   1  99
4                18.214165   1  99
5                15.017885   1  99
6                16.408631   1  99
7                17.131898   1  99
8                15.533981   1  96
9                15.839461   1  99
10               20.554965   1  98
11               16.644595   1  99
12               16.434299   1  99
13               16.411972   1  99
14               17.020195   1  99
15               16.488061   1  99
16               17.710705   1  99
17               16.119392   1  99
18               19.515857   1  99
19               16.950390   1  99
20               16.360832   1  99
21               23.434286   1  99

**Applying an aggregate value to each value you have grouped by**

In [ ]:
#Create a new column - 'max_order'

#Define what goes in it.
#first group by users
#then each user gets assisnged a value which is their maximum number of orders

df_subset['max_order'] = df_subset.groupby(['user_id'])['order_number'].transform(np.max)

/tmp/ipython-input-70-4046173782.py:7: FutureWarning: The provided callable <function max at 0x7a3d86139800> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df_subset['max_order'] = df_subset.groupby(['user_id'])['order_number'].transform(np.max)
/tmp/ipython-input-70-4046173782.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['max_order'] = df_subset.groupby(['user_id'])['order_number'].transform(np.max)

In [ ]:
df_subset.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_days,busiest_time,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,2907475,96682,prior,23,4,14,14.0,3,1,both,Mid-range product,Least busy days,Busiest time,23
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,3038506,39081,prior,16,2,17,30.0,5,0,both,Mid-range product,Regularly busy days,Regularly busy time,29
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,3185203,95847,prior,49,1,7,3.0,6,1,both,Mid-range product,Busiest days,Regularly busy time,93
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,1830804,14910,prior,56,4,12,6.0,3,1,both,Mid-range product,Least busy days,Regularly busy time,56
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Busiest days,Regularly busy time,25

In [ ]:
#Stopping pd from only showing a limited number of rows when using head etc

pd.options.display.max_rows = None

In [ ]:
#Now looking at first 100 rows

df_subset.head(100)

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_days,busiest_time,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,2907475,96682,prior,23,4,14,14.0,3,1,both,Mid-range product,Least busy days,Busiest time,23
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,3038506,39081,prior,16,2,17,30.0,5,0,both,Mid-range product,Regularly busy days,Regularly busy time,29
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,3185203,95847,prior,49,1,7,3.0,6,1,both,Mid-range product,Busiest days,Regularly busy time,93
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,1830804,14910,prior,56,4,12,6.0,3,1,both,Mid-range product,Least busy days,Regularly busy time,56
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,prior,16,1,7,26.0,7,0,both,Mid-range product,Busiest days,Regularly busy time,25
5,0,1,Chocolate Sandwich Cookies,61,19,5.8,1157193,146872,prior,61,5,9,2.0,1,1,both,Mid-range product,Regularly busy days,Regularly busy time,98
6,0,1,Chocolate Sandwich Cookies,61,19,5.8,127530,30310,prior,7,0,10,7.0,3,1,both,Mid-range product,Busiest days,Busiest time,7
7,0,1,Chocolate Sandwich Cookies,61,19,5.8,1618214,125644,prior,11,1,9,7.0,4,1,both,Mid-range product,Busiest days,Regularly busy time,11
8,0,1,Chocolate Sandwich Cookies,61,19,5.8,1136196,84766,prior,40,2,11,11.0,4,1,both,Mid-range product,Regularly busy days,Busiest time,40
9,0,1,Chocolate Sandwich Cookies,61,19,5.8,491203,159791,prior,17,5,0,3.0,18,0,both,Mid-range product,Regularly busy days,Regularly busy time,94
10,0,1,Chocolate Sandwich Cookies,61,19,5.8,1210960,158844,prior,23,3,15,0.0,8,1,both,Mid-range product,Least busy days,Regularly busy time,40
11,0,1,Chocolate Sandwich Cookies,61,19,5.8,1503284,52564,prior,41,3,21,6.0,4,1,both,Mid-range product,Least busy days,Regularly busy time,44
12,0,1,Chocolate Sandwich Cookies,61,19,5.8,2935413,111073,prior,20,5,18,1.0,15,0,both,Mid-range product,Regularly busy days,Regularly busy time,43
13,0,1,Chocolate Sandwich Cookies,61,19,5.8,82631,60380,prior,26,4,10,10.0,2,1,both,Mid-range product,Least busy days,Busiest time,26
14,0,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,prior,4,2,14,14.0,15,0,both,Mid-range product,Regularly busy days,Busiest time,20
15,0,1,Chocolate Sandwich Cookies,61,19,5.8,1969070,160886,prior,3,2,22,10.0,3,0,both,Mid-range product,Regularly busy days,Regularly busy time,6
16,0,1,Chocolate Sandwich Cookies,61,19,5.8,966548,137500,prior,21,1,20,5.0,11,1,both,Mid-range product,Busiest days,Regularly busy time,22
17,0,1,Chocolate Sandwich Cookies,61,19,5.8,2691777,17996,prior,2,3,7,16.0,3,0,both,Mid-range product,Least busy days,Regularly busy time,6
18,0,1,Chocolate Sandwich Cookies,61,19,5.8,708668,44790,prior,2,5,15,16.0,2,0,both,Mid-range product,Regularly busy days,Regularly busy time,25
19,0,1,Chocolate Sandwich Cookies,61,19,5.8,2532468,50898,prior,27,3,12,6.0,10,1,both,Mid-range product,Least busy days,Regularly busy time,38
20,0,1,Chocolate Sandwich Cookies,61,19,5.8,2517311,119163,prior,29,3,12,5.0,1,0,both,Mid-range product,Least busy days,Regularly busy time,29
21,0,1,Chocolate Sandwich Cookies,61,19,5.8,984729,158591,prior,34,5,13,14.0,2,1,both,Mid-range product,Regularly busy days,Regularly busy time,34
22,0,1,Chocolate Sandwich Cookies,61,19,5.8,161236,60693,prior,34,6,13,6.0,4,0,both,Mid-range product,Regularly busy days,Regularly busy time,34
23,0,1,Chocolate Sandwich Cookies,61,19,5.8,878108,34919,prior,24,6,12,1.0,5,1,both,Mid-range product,Regularly busy days,Regularly busy time,54
24,0,1,Chocolate Sandwich Cookies,61,19,5.8,236447,199181,prior,12,5,14,2.0,4,1,both,Mid-range product,Regularly busy days,Busiest time,21
25,0,1,Chocolate Sandwich Cookies,61,19,5.8,3232117,121913,prior,3,0,16,30.0,3,0,both,Mid-range product,Busiest days,Regularly busy time,4
26,0,1,Chocolate Sandwich Cookies,61,19,5.8,2017166,196224,prior,9,2,3,3.0,4,1,both,Mid-range product,Regularly busy days,Least busy time,92
27,0,1,Chocolate Sandwich Cookies,61,19,5.8,2621797,186821,prior,4,0,17,8.0,4,0,both,Mid-range product,Busiest days,Regularly busy time,20
28,0,1,Chocolate Sandwich Cookies,61,19,5.8,3070909,111982,prior,49,4,12,1.0,1,1,both,Mid-range product,Least busy days,Regularly busy time,72
29,0,1,Chocolate Sandwich Cookies,61,19,5.8,647660,115516,prior,31,2,11,8.0,9,1,both,Mid-range product,Regularly busy days,Busiest time,49
30,0,1,Chocolate Sandwich Cookies,61,19,5.8,1210324,110832,prior,2,2,10,30.0,3,0,both,Mid-range product,Regularly busy days,Busiest time,2
31,0,1,Chocolate Sandwich Cookies,61,19,5.8,2485793,157915,prior,13,3,17,16.0,1,1,both,Mid-range product,Least busy days,Regularly busy time,28
32,0,1,Chocolate Sandwich Cookies,61,19,5.8,1071576,96604,prior,23,5,12,8.0,8,0,both,Mid-range product,Regularly busy days,Regularly busy time,50
33,0,1,Chocolate Sandwich Cookies,61,19,5.8,378189,164788,prior,7,3,19,30.0,2,0,both,Mid-range product,Least busy days,Regularly busy time,7
34,0,1,Chocolate Sandwich Cookies,61,19,5.8,1148126,158591,prior,11,5,11,4.0,2,1,both,Mid-range product,Regularly busy days,Busiest time,34
35,0,1,Chocolate Sandwich Cookies,61,19,5.8,1778932,141947,prior,10,2,15,8.0,5,1,both,Mid-range product,Regularly busy days,Regularly busy time,25
36,0,1,Chocolate Sandwich Cookies,61,19,5.8,1870503,163386,prior,8,2,8,19.0,21,1,both,Mid-range product,Regularly busy days,Regularly busy time,21
37,0,1,Chocolate Sandwich Cookies,61,19,5.8,1205843,35890,prior,11,2,10,30.0,2,1,both,Mid-range product,Regularly busy days,Busiest time,17
38,0,1,Chocolate Sandwich Cookies,61,19,5.8,1415700,133169,prior,7,3,10,9.0,1,0,both,Mid-range product,Least busy days,Busiest time,23
39,0,1,Chocolate Sandwich Cookies,61,19,5.8,3414191,91160,prior,52,6,21,0.0,4,1,both,Mid-range product,Regularly busy days,Regularly busy time,66
40,0,1,Chocolate Sandwich Cookies,61,19,5.8,859646,57996,prior,48,2,17,5.0,12,1,both,Mid-range product,Regularly busy days,Regularly busy time,61
41,0,1,Chocolate Sandwich Cookies,61,19,5.8,2701828,37613,prior,24,2,17,1.0,3,1,both,Mid-range product,Regularly busy days,Regularly busy time,59
42,0,1,Chocolate Sandwich Cookies,61,19,5.8,137216,186650,prior,8,3,14,16.0,3,0,both,Mid-range product,Least busy days,Busiest time,80
43,0,1,Chocolate Sandwich Cookies,61,19,5.8,3006328,35196,prior,3,0,14,30.0,9,0,both,Mid-range product,Busiest days,Busiest time,21
44,0,1,Chocolate Sandwich Cookies,61,19,5.8,1943351,144159,prior,13,0,10,9.0,30,1,both,Mid-range product,Busiest days,Busiest time,19
45,0,1,Chocolate Sandwich Cookies,61,19,5.8,437459,109572,prior,59,3,16,1.0,1,1,both,Mid-range product,Least busy days,Regularly busy time,59
46,0,1,Chocolate Sandwich Cookies,61,19,5.8,604560,120718,prior,30,6,16,22.0,6,1,both,Mid-range product,Regularly busy days,Regularly busy time,30
47,0,1,Chocolate Sandwich Cookies,61,19,5.8,802417,22793,prior,4,4,11,10.0,5,1,both,Mid-range product,Least busy days,Busiest time,15
48,0,1,Chocolate Sandwich Cookies,61,19,5.8,1429388,108367,prior,3,3,12,30.0,2,0,both,Mid-range product,Least busy days,Regularly busy time,8
49,0,1,Chocolate Sandwich Cookies,61,19,5.8,3343933,145828,prior,3,3,22,0.0,4,0,both,Mid-range product,Least busy days,Regularly busy time,3
50,0,1,Chocolate Sandwich Cookies,61,19,5.8,3178201,86047,prior,12,3,15,1.0,10,0,both,Mid-range product,Least busy days,Regularly busy time,19
51,0,1,Chocolate Sandwich Cookies,61,19,5.8,1568474,181697,prior,18,2,16,5.0,15,1,both,Mid-range product,Regularly busy days,Regularly busy time,47
52,0,1,Chocolate Sandwich Cookies,61,19,5.8,1074808,140575,prior,19,3,16,6.0,2,0,both,Mid-range product,Least busy days,Regularly busy time,19
53,0,1,Chocolate Sandwich Cookies,61,19,5.8,2895953,129539,prior,20,0,12,6.0,4,0,both,Mid-range product,Busiest days,Regularly busy time,33
54,0,1,Chocolate Sandwich Cookies,61,19,5.8,3206006,15172,prior,6,5,11,10.0,4,0,both,Mid-range product,Regularly busy days,Busiest time,51
55,0,1,Chocolate Sandwich Cookies,61,19,5.8,309038,181697,prior,16,1,16,8.0,13,1,both,Mid-range product,Busiest days,Regularly busy time,47
56,0,1,Chocolate Sandwich Cookies,61,19,5.8,2896032,115682,prior,14,2,8,23.0,3,1,both,Mid-range product,Regularly busy days,Regularly busy time,17
57,0,1,Chocolate Sandwich Cookies,61,19,5.8,3150098,86777,prior,8,1,13,6.0,11,0,both,Mid-range product,Busiest days,Regularly busy time,8
58,0,1,Chocolate Sandwich Cookies,61,19,5.8,776524,112462,prior,5,6,14,22.0,1,1,both,Mid-range product,Regularly busy days,Busiest time,39
59,0,1,Chocolate Sandwich Cookies,61,19,5.8,850951,12470,prior,68,1,11,6.0,8,1,both,Mid-range product,Busiest days,Busiest time,68
60,0,1,Chocolate Sandwich Cookies,61,19,5.8,29334,30345,prior,6,3,10,30.0,5,1,both,Mid-range product,Least busy days,Busiest time,6
61,0,1,Chocolate Sandwich Cookies,61,19,5.8,2641319,21876,prior,2,4,10,30.0,5,0,both,Mid-range product,Least busy days,Busiest time,3
62,0,1,Chocolate Sandwich Cookies,61,19,5.8,689860,108367,prior,5,2,9,14.0,3,1,both,Mid-range product,Regularly busy days,Regularly busy time,8
63,0,1,Chocolate Sandwich Cookies,61,19,5.8,1742695,35717,prior,24,3,7,1.0,4,1,both,Mid-range product,Least busy days,Regularly busy time,27
64,0,1,Chocolate Sandwich Cookies,61,19,5.8,1104934,136801,prior,30,5,9,7.0,13,1,both,Mid-range product,Regularly busy days,Regularly busy time,48
65,0,1,Chocolate Sandwich Cookies,61,19,5.8,1860749,35890,prior,6,2,19,9.0,16,0,both,Mid-range product,Regularly busy days,Regularly busy time,17
66,0,1,Chocolate Sandwich Cookies,61,19,5.8,1359987,114091,prior,8,2,18,21.0,2,0,both,Mid-range product,Regularly busy days,Regularly busy time,8
67,0,1,Chocolate Sandwich Cookies,61,19,5.8,1428312,146872,prior,45,1,5,2.0,2,1,both,Mid-range product,Busiest days,Regularly busy time,98
68,0,1,Chocolate Sandwich Cookies,61,19,5.8,629190,22667,prior,38,5,18,0.0,1,1,both,Mid-range product,Regularly busy days,Regularly busy time,48
69,0,1,Chocolate Sandwich Cookies,61,19,5.8,2337178,55640,prior,4,2,12,30.0,1,1,both,Mid-range product,Regularly busy days,Regularly busy time,4
70,0,1,Chocolate Sandwich Cookies,61,19,5.8,580414,91811,prior,8,2,10,8.0,2,1,both,Mid-range product,Regularly busy days,Busiest time,8
71,0,1,Chocolate Sandwich Cookies,61,19,5.8,1311315,134184,prior,1,6,18,NaN,19,0,both,Mid-range product,Regularly busy days,Regularly busy time,1
72,0,1,Chocolate Sandwich Cookies,61,19,5.8,1262933,168480,prior,3,5,13,27.0,3,0,both,Mid-range product,Regularly busy days,Regularly busy time,3
73,0,1,Chocolate Sandwich Cookies,61,19,5.8,2324735,196224,prior,38,6,11,1.0,5,1,both,Mid-range product,Regularly busy days,Busiest time,92
74,0,1,Chocolate Sandwich Cookies,61,19,5.8,1969363,117713,prior,4,0,15,30.0,13,1,both,Mid-range product,Busiest days,Regularly busy time,4
75,0,1,Chocolate Sandwich Cookies,61,19,5.8,390978,24324,prior,13,2,21,7.0,15,0,both,Mid-range product,Regularly busy days,Regularly busy time,26
76,0,1,Chocolate Sandwich Cookies,61,19,5.8,3177270,87450,prior,5,1,18,15.0,4,0,both,Mid-range product,Busiest days,Regularly busy time,6
77,0,1,Chocolate Sandwich Cookies,61,19,5.8,1615452,133927,prior,2,3,19,30.0,2,0,both,Mid-range product,Least busy days,Regularly busy time,2
78,0,1,Chocolate Sandwich Cookies,61,19,5.8,413039,170257,prior,15,5,8,3.0,3,1,both,Mid-range product,Regularly busy days,Regularly busy time,39
79,0,1,Chocolate Sandwich Cookies,61,19,5.8,2396469,146872,prior,19,3,5,1.0,3,1,both,Mid-range product,Least busy days,Regularly busy time,98
80,0,1,Chocolate Sandwich Cookies,61,19,5.8,1675781,90845,prior,4,1,12,4.0,3,0,both,Mid-range product,Busiest days,Regularly busy time,4
81,0,1,Chocolate Sandwich Cookies,61,19,5.8,1190553,50898,prior,31,4,16,3.0,9,1,both,Mid-range product,Least busy days,Regularly busy time,38
82,0,1,Chocolate Sandwich Cookies,61,19,5.8,3103728,203337,prior,6,0,5,30.0,9,0,both,Mid-range product,Busiest days,Regularly busy time,6
83,0,1,Chocolate Sandwich Cookies,61,19,5.8,2148413,204390,prior,20,4,11,7.0,5,1,both,Mid-range product,Least busy days,Busiest time,20
84,0,1,Chocolate Sandwich Cookies,61,19,5.8,76483,131925,prior,8,3,16,30.0,4,0,both,Mid-range product,Least busy days,Regularly busy time,12
85,0,1,Chocolate Sandwich Cookies,61,19,5.8,289511,204855,prior,7,1,17,30.0,1,0,both,Mid-range product,Busiest days,Regularly busy time,7
86,0,1,Chocolate Sandwich Cookies,61,19,5.8,431915,29192,prior,17,0,13,30.0,1,1,both,Mid-range product,Busiest days,Regularly busy time,21
87,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,1,15,NaN,30,0,both,Mid-range product,Busiest days,Regularly busy time,22
88,0,1,Chocolate Sandwich Cookies,61,19,5.8,2623223,205214,prior,8,0,17,12.0,18,1,both,Mid-range product,Busiest days,Regularly busy time,8
89,0,1,Chocolate Sandwich Cookies,61,19,5.8,2652466,175609,prior,11,1,21,0.0,8,0,both,Mid-range product,Busiest days,Regularly busy time,11
90,0,1,Chocolate Sandwich Cookies,61,19,5.8,317606,57585,prior,10,4,10,9.0,5,1,both,Mid-range product,Least busy days,Busiest time,27
91,0,1,Chocolate Sandwich Cookies,61,19,5.8,1399940,33838,prior,16,4,9,1.0,5,0,both,Mid-range product,Least busy days,Regularly busy time,16
92,0,1,Chocolate Sandwich Cookies,61,19,5.8,618087,157800,prior,26,0,10,10.0,1,1,both,Mid-range product,Busiest days,Busiest time,33
93,0,1,Chocolate Sandwich Cookies,61,19,5.8,1487311,115353,prior,12,1,14,13.0,9,1,both,Mid-range product,Busiest days,Busiest time,22
94,0,1,Chocolate Sandwich Cookies,61,19,5.8,2130307,71390,prior,1,0,19,NaN,26,0,both,Mid-range product,Busiest days,Regularly busy time,2
95,0,1,Chocolate Sandwich Cookies,61,19,5.8,2405915,65777,prior,40,3,10,9.0,1,1,both,Mid-range product,Least busy days,Busiest time,43
96,0,1,Chocolate Sandwich Cookies,61,19,5.8,538513,143478,prior,16,5,16,6.0,6,0,both,Mid-range product,Regularly busy days,Regularly busy time,24
97,0,1,Chocolate Sandwich Cookies,61,19,5.8,1592733,75369,prior,80,4,14,2.0,1,0,both,Mid-range product,Least busy days,Busiest time,80
98,0,1,Chocolate Sandwich Cookies,61,19,5.8,1508257,57585,prior,7,4,19,9.0,3,1,both,Mid-range product,Least busy days,Regularly busy time,27
99,0,1,Chocolate Sandwich Cookies,61,19,5.8,2282921,125331,prior,3,3,12,6.0,6,1,both,Mid-range product,Least busy days,Regularly busy time,3

**Use loc() to create an if-else condition and apply to a new column**

In [ ]:
#Using loc() to set up an if-else condition and to name different tupes of customer based on how many orderrs placed

df_subset.loc[df_subset['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

/tmp/ipython-input-74-3892155425.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset.loc[df_subset['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [ ]:
df_subset.loc[(df_subset['max_order'] <= 40) & (df_subset['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [ ]:
df_subset.loc[df_subset['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [ ]:
#checking how many of each type of customer this produces

df_subset['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    469176
Loyal customer      293248
New customer        237576
Name: count, dtype: int64

In [ ]:
#checking the sum of the loyalty flags adds up to 1 million

df_subset['loyalty_flag'].value_counts(dropna = False).sum()

np.int64(1000000)

In [ ]:
#looking at head of only certain rows to check is doing  what should

df_subset[['user_id', 'loyalty_flag', 'max_order']].head(60)

    user_id      loyalty_flag  max_order
0     96682  Regular customer         23
1     39081  Regular customer         29
2     95847    Loyal customer         93
3     14910    Loyal customer         56
4       777  Regular customer         25
5    146872    Loyal customer         98
6     30310      New customer          7
7    125644  Regular customer         11
8     84766  Regular customer         40
9    159791    Loyal customer         94
10   158844  Regular customer         40
11    52564    Loyal customer         44
12   111073    Loyal customer         43
13    60380  Regular customer         26
14    10708  Regular customer         20
15   160886      New customer          6
16   137500  Regular customer         22
17    17996      New customer          6
18    44790  Regular customer         25
19    50898  Regular customer         38
20   119163  Regular customer         29
21   158591  Regular customer         34
22    60693  Regular customer         34
23    34919    Loyal customer         54
24   199181  Regular customer         21
25   121913      New customer          4
26   196224    Loyal customer         92
27   186821  Regular customer         20
28   111982    Loyal customer         72
29   115516    Loyal customer         49
30   110832      New customer          2
31   157915  Regular customer         28
32    96604    Loyal customer         50
33   164788      New customer          7
34   158591  Regular customer         34
35   141947  Regular customer         25
36   163386  Regular customer         21
37    35890  Regular customer         17
38   133169  Regular customer         23
39    91160    Loyal customer         66
40    57996    Loyal customer         61
41    37613    Loyal customer         59
42   186650    Loyal customer         80
43    35196  Regular customer         21
44   144159  Regular customer         19
45   109572    Loyal customer         59
46   120718  Regular customer         30
47    22793  Regular customer         15
48   108367      New customer          8
49   145828      New customer          3
50    86047  Regular customer         19
51   181697    Loyal customer         47
52   140575  Regular customer         19
53   129539  Regular customer         33
54    15172    Loyal customer         51
55   181697    Loyal customer         47
56   115682  Regular customer         17
57    86777      New customer          8
58   112462  Regular customer         39
59    12470    Loyal customer         68

# EXERCISE

The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

**Group by and check stats for those grouped values**

In [ ]:
#So we want to group by 'loyatly_flag' and then look at the stats of the 'prices'

df_subset.groupby('loyalty_flag').agg({'prices': ['mean', 'median', 'min', 'max']})

                    prices
                      mean median  min   max
loyalty_flag
Loyal customer    7.691334    7.2  1.0  25.0
New customer      7.671764    7.2  1.0  25.0
Regular customer  7.693354    7.2  1.0  25.0

There's very little difference in the prices of products these three types of customer buy

The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:
If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

**Create a new column and define what goes in it**

In [ ]:
#Create a new column - 'average_order'

#Define what goes in it.
#first group by users
#then each user gets assigned a value which is their average order price

df_subset['average_order'] = df_subset.groupby(['user_id'])['prices'].transform(np.mean)

/tmp/ipython-input-81-1161974603.py:7: FutureWarning: The provided callable <function mean at 0x7a3d8613a200> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_subset['average_order'] = df_subset.groupby(['user_id'])['prices'].transform(np.mean)
/tmp/ipython-input-81-1161974603.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['average_order'] = df_subset.groupby(['user_id'])['prices'].transform(np.mean)

In [ ]:
#Use loc() to set up an if-else condition and to name different tupes of spenders based on the average price of products they buy

df_subset.loc[df_subset['average_order'] < 10, 'spending_flag'] = 'Low spender'

/tmp/ipython-input-82-3133084299.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset.loc[df_subset['average_order'] < 10, 'spending_flag'] = 'Low spender'

In [ ]:
df_subset.loc[df_subset['average_order'] >= 10, 'spending_flag'] = 'High spender'

In [ ]:
#checking how many of each type of customer this produces

df_subset['spending_flag'].value_counts(dropna = False)

spending_flag
Low spender     893025
High spender    106975
Name: count, dtype: int64

In [ ]:
#checking the sum of the spending flags adds up to 1 million

df_subset['spending_flag'].value_counts(dropna = False).sum()

np.int64(1000000)

In [ ]:
#looking at head of only certain rows to check is doing  what should

df_subset[['user_id', 'spending_flag', 'average_order']].head(60)

    user_id spending_flag  average_order
0     96682   Low spender       5.440000
1     39081   Low spender       9.383333
2     95847   Low spender       6.388571
3     14910   Low spender       6.914286
4       777   Low spender       7.580000
5    146872  High spender      10.943478
6     30310   Low spender       4.766667
7    125644   Low spender       5.800000
8     84766   Low spender       3.933333
9    159791   Low spender       5.328571
10   158844   Low spender       5.635294
11    52564  High spender      10.840000
12   111073   Low spender       8.162500
13    60380   Low spender       7.611111
14    10708   Low spender       6.926667
15   160886   Low spender       4.266667
16   137500   Low spender       7.166667
17    17996   Low spender       7.433333
18    44790   Low spender       4.681818
19    50898   Low spender       6.004348
20   119163   Low spender       8.300000
21   158591   Low spender       4.233333
22    60693   Low spender       9.300000
23    34919   Low spender       6.400000
24   199181   Low spender       3.520000
25   121913   Low spender       5.800000
26   196224   Low spender       3.175000
27   186821   Low spender       5.527273
28   111982   Low spender       4.580000
29   115516   Low spender       5.135000
30   110832   Low spender       5.800000
31   157915   Low spender       7.710000
32    96604   Low spender       7.222222
33   164788   Low spender       9.125000
34   158591   Low spender       4.233333
35   141947   Low spender       6.766667
36   163386   Low spender       4.517647
37    35890   Low spender       6.363636
38   133169   Low spender       6.040000
39    91160  High spender      10.933333
40    57996   Low spender       6.362500
41    37613   Low spender       6.900000
42   186650   Low spender       4.466667
43    35196   Low spender       5.916667
44   144159   Low spender       5.366667
45   109572   Low spender       6.966667
46   120718   Low spender       8.000000
47    22793   Low spender       6.800000
48   108367   Low spender       5.166667
49   145828   Low spender       3.400000
50    86047   Low spender       5.837500
51   181697   Low spender       9.077049
52   140575   Low spender       6.400000
53   129539   Low spender       8.600000
54    15172   Low spender       8.320000
55   181697   Low spender       9.077049
56   115682   Low spender       8.400000
57    86777   Low spender       8.350000
58   112462   Low spender       6.283333
59    12470   Low spender       4.657143

In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers.

Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:

If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

**2nd version - Create a new column and define what goes in it**

In [ ]:
#Create a new column - 'order_frequency'

#Define what goes in it.
#first group by users
#then each user gets assigned a value which is their median frequency of order

df_subset['order_frequency'] = df_subset.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

/tmp/ipython-input-87-859163050.py:7: FutureWarning: The provided callable <function median at 0x7a3d8359b880> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df_subset['order_frequency'] = df_subset.groupby(['user_id'])['days_since_prior_order'].transform(np.median)
/tmp/ipython-input-87-859163050.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['order_frequency'] = df_subset.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [ ]:
#Use loc() to set up an if-else condition and to name different tupes of users based on how frequently they buy

df_subset.loc[df_subset['order_frequency'] >20, 'frequency_flag'] = 'Non-frequent customer'

/tmp/ipython-input-88-3135190080.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset.loc[df_subset['order_frequency'] >20, 'frequency_flag'] = 'Non-frequent customer'

In [ ]:
df_subset.loc[(df_subset['order_frequency'] <= 20) & (df_subset['order_frequency'] > 10), 'frequency_flag'] = 'Regular customer'

In [ ]:
df_subset.loc[df_subset['order_frequency'] <=10, 'frequency_flag'] = 'Frequent customer'

In [ ]:
#checking how many of each type of customer this produces

df_subset['frequency_flag'].value_counts(dropna = False)

frequency_flag
Frequent customer        648799
Regular customer         214651
Non-frequent customer    127038
NaN                        9512
Name: count, dtype: int64

In [ ]:
#checking the sum of the frequency flags adds up to 1 million

df_subset['frequency_flag'].value_counts(dropna = False).sum()

np.int64(1000000)

In [ ]:
#looking at head of only certain rows to check is doing  what should

df_subset[['user_id', 'frequency_flag', 'order_frequency']].head(60)

    user_id         frequency_flag  order_frequency
0     96682       Regular customer             11.5
1     39081       Regular customer             10.5
2     95847      Frequent customer              4.0
3     14910      Frequent customer              5.0
4       777       Regular customer             12.0
5    146872      Frequent customer              2.0
6     30310      Frequent customer              7.0
7    125644      Frequent customer              7.0
8     84766      Frequent customer              3.5
9    159791      Frequent customer              3.0
10   158844      Frequent customer              6.5
11    52564      Frequent customer              6.0
12   111073      Frequent customer              6.0
13    60380       Regular customer             14.0
14    10708       Regular customer             14.0
15   160886       Regular customer             19.0
16   137500      Frequent customer              7.0
17    17996  Non-frequent customer             30.0
18    44790       Regular customer             14.0
19    50898      Frequent customer              3.5
20   119163      Frequent customer              5.0
21   158591      Frequent customer              4.0
22    60693      Frequent customer              8.0
23    34919      Frequent customer              7.0
24   199181      Frequent customer              2.0
25   121913  Non-frequent customer             30.0
26   196224      Frequent customer              1.0
27   186821      Frequent customer              7.0
28   111982      Frequent customer              4.0
29   115516      Frequent customer              7.5
30   110832  Non-frequent customer             30.0
31   157915       Regular customer             14.0
32    96604      Frequent customer              7.5
33   164788       Regular customer             20.0
34   158591      Frequent customer              4.0
35   141947      Frequent customer              7.0
36   163386       Regular customer             15.0
37    35890  Non-frequent customer             21.0
38   133169      Frequent customer              9.0
39    91160      Frequent customer              2.5
40    57996      Frequent customer              6.0
41    37613      Frequent customer              5.0
42   186650      Frequent customer              6.0
43    35196  Non-frequent customer             24.5
44   144159      Frequent customer              6.5
45   109572      Frequent customer              6.0
46   120718  Non-frequent customer             20.5
47    22793       Regular customer             12.5
48   108367  Non-frequent customer             26.0
49   145828      Frequent customer              0.0
50    86047      Frequent customer              8.0
51   181697      Frequent customer              3.0
52   140575      Frequent customer              6.5
53   129539       Regular customer             13.0
54    15172      Frequent customer              9.0
55   181697      Frequent customer              3.0
56   115682  Non-frequent customer             23.0
57    86777       Regular customer             18.0
58   112462       Regular customer             13.0
59    12470      Frequent customer              4.0

**Reviewing NaN values**

In [ ]:
#Want to look at 20 NaNs to see if we can see what is going on
#only in columns 'user_id', 'frequency_flag', 'order_frequency', 'days-since_prior_order'

df_subset[df_subset['frequency_flag'].isna()][['user_id','order_frequency', 'days_since_prior_order', 'frequency_flag']].head(20)

      user_id  order_frequency  days_since_prior_order frequency_flag
71     134184              NaN                     NaN            NaN
105     46365              NaN                     NaN            NaN
111     47918              NaN                     NaN            NaN
117    149303              NaN                     NaN            NaN
267     62604              NaN                     NaN            NaN
284    171881              NaN                     NaN            NaN
503    181478              NaN                     NaN            NaN
538     66517              NaN                     NaN            NaN
567    101213              NaN                     NaN            NaN
573    119066              NaN                     NaN            NaN
600    102979              NaN                     NaN            NaN
675     33316              NaN                     NaN            NaN
679     64445              NaN                     NaN            NaN
921    127177              NaN                     NaN            NaN
1035    32790              NaN                     NaN            NaN
1050    82374              NaN                     NaN            NaN
1142    40363              NaN                     NaN            NaN
1280   130195              NaN                     NaN            NaN
1513   137790              NaN                     NaN            NaN
1514    16021              NaN                     NaN            NaN

So, we're getting NaNs where 'days_since_prior_order' = NaN

**Renaming values**

Want to rename all the NaNs in 'frequency_flag' as No orders 30 (No orders in past 30 days)

I initially did this:

df_subset['frequency_flag'] = df_subset['frequency_flag'].fillna('No orders 30')

In [1]:
#Wants me to use loc() instead - so this would be..

df_subset.loc[df_subset['frequency_flag'].isna(), 'frequency_flag'] = 'No orders 30'

NameError: name 'df_subset' is not defined

In [ ]:
#checking how many of each type of customer this produces

df_subset['frequency_flag'].value_counts(dropna = False)

frequency_flag
Frequent customer        648799
Regular customer         214651
Non-frequent customer    127038
No orders 30               9512
Name: count, dtype: int64

Gives a more satisfying / useful result!

In [ ]:
#Export to drive#

df_subset.to_pickle('/content/drive/MyDrive/group_aggregate.pkl')