import pandas and a dataset

Group by and show stats

Renaming columns when showing the stats (not ‘min’ but ‘min_age’ etc)

Groupby more than one column

Import new data - setting data types

Groupby 2 columns ' 'sortby' count of another column

Create new column - use loc() and if-else to populate - with a default value

Use new column for a new groupby

View of the df with a groupbby applied

Another way - using loc() - to show the df with just one value from a column

**import pandas and a dataset**

In [ ]:
import pandas as pd

In [ ]:
data = {"Team": ["Red Sox", "Red Sox", "Red Sox", "Red Sox", "Red Sox", "Red Sox", "Yankees", "Yankees", "Yankees", "Yankees", "Yankees", "Yankees"],
		"Pos": ["Pitcher", "Pitcher", "Pitcher", "Not Pitcher", "Not Pitcher", "Not Pitcher", "Pitcher", "Pitcher", "Pitcher", "Not Pitcher", "Not Pitcher", "Not Pitcher"],
		"Age": [24, 28, 40, 22, 29, 33, 31, 26, 21, 36, 25, 31]}
df = pd.DataFrame(data)
print(df)

       Team          Pos  Age
0   Red Sox      Pitcher   24
1   Red Sox      Pitcher   28
2   Red Sox      Pitcher   40
3   Red Sox  Not Pitcher   22
4   Red Sox  Not Pitcher   29
5   Red Sox  Not Pitcher   33
6   Yankees      Pitcher   31
7   Yankees      Pitcher   26
8   Yankees      Pitcher   21
9   Yankees  Not Pitcher   36
10  Yankees  Not Pitcher   25
11  Yankees  Not Pitcher   31

**Group by and show stats**

In [ ]:
df.groupby('Team').agg({'Age': ['mean', 'min', 'max']})

               Age
              mean min max
Team
Red Sox  29.333333  22  40
Yankees  28.333333  21  36

In [ ]:
# group by Team, get mean, min, and max value of Age for each value of Team.
grouped_single = df.groupby('Team').agg({'Age': ['mean', 'min', 'max']})

print(grouped_single)

               Age
              mean min max
Team
Red Sox  29.333333  22  40
Yankees  28.333333  21  36

**Renaming columns when showing the stats**

In [ ]:
# rename columns
grouped_single.columns = ['age_mean', 'age_min', 'age_max']

# reset index to get grouped columns back
grouped_single = grouped_single.reset_index()

print(grouped_single)

      Team   age_mean  age_min  age_max
0  Red Sox  29.333333       22       40
1  Yankees  28.333333       21       36

**Groupby more than one column**

In [ ]:
#Grouping by multiple columns

grouped_multiple = df.groupby(['Team', 'Pos']).agg({'Age': ['mean', 'min', 'max']})
grouped_multiple.columns = ['age_mean', 'age_min', 'age_max']
grouped_multiple = grouped_multiple.reset_index()
print(grouped_multiple)

      Team          Pos   age_mean  age_min  age_max
0  Red Sox  Not Pitcher  28.000000       22       33
1  Red Sox      Pitcher  30.666667       24       40
2  Yankees  Not Pitcher  30.666667       25       36
3  Yankees      Pitcher  26.000000       21       31

**Import new data - setting data types**

In [ ]:
#Set data types

dtypes = {
    "first_name": "category",
    "gender": "category",
    "type": "category",
    "state": "category",
    "party": "category",
}

In [ ]:
#Import legislators .csv as df_leg

##This is saved in my top level of Section 4

#Only importing the columns we've specified above, and 'birthday' and 'last_name'

df_leg = pd.read_csv("legislators-historical.csv",
    dtype=dtypes,
    usecols=list(dtypes) + ["birthday", "last_name"],
    parse_dates=["birthday"]
)

In [ ]:
df_leg.head()

  last_name  first_name   birthday gender type state                party
0   Bassett     Richard 1745-04-02      M  sen    DE  Anti-Administration
1     Bland  Theodorick 1742-03-21      M  rep    VA                  NaN
2     Burke     Aedanus 1743-06-16      M  rep    SC                  NaN
3   Carroll      Daniel 1730-07-22      M  rep    MD                  NaN
4    Clymer      George 1739-03-16      M  rep    PA                  NaN

In [ ]:
df_leg.dtypes

last_name             object
first_name          category
birthday      datetime64[ns]
gender              category
type                category
state               category
party               category
dtype: object

**Groupby 2 columns ' 'sortby' count of another column**

In [ ]:
n_by_state_party = df_leg.groupby(["state", "party"])["last_name"].count()

/tmp/ipython-input-24-2877351181.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  n_by_state_party = df_leg.groupby(["state", "party"])["last_name"].count()

In [ ]:
n_by_state_party.head(20)

state  party
AK     Adams                         0
       Adams Democrat                0
       American                      0
       American Labor                0
       Anti Jackson                  0
       Anti Jacksonian               0
       Anti Masonic                  0
       Anti-Administration           0
       Anti-Jacksonian               0
       Anti-Lecompton Democrat       0
       Coalitionist                  0
       Conservative                  0
       Conservative Republican       0
       Constitutional Unionist       0
       Crawford Republican           0
       Democrat                      8
       Democrat-Liberal              0
       Democratic Republican         0
       Democratic and Union Labor    0
       Farmer-Labor                  0
Name: last_name, dtype: int64

**Create new column - use loc() and if-else to populate - with a default value**

In [ ]:
#Using loc() to set up an if-else condition and to categorise inot 3 different types of party

df_leg['3_parties'] = 'Other'  # default to Other

In [ ]:
df_leg.loc[df_leg['party'] == 'Republican', '3_parties'] = 'Republican'
df_leg.loc[df_leg['party'] == 'Democrat', '3_parties'] = 'Democrat'

In [ ]:
# Use boolean indexing to select rows where 'party' is not 'Democrat' or 'Republican'
## using this method - don't need this df_leg.loc[~df_leg['party'].isin(['Democrat', 'Republican']), '3_parties'] = 'Other'

In [ ]:
#Checking what the new column looks like

df_leg['3_parties'].value_counts()

3_parties
Democrat      5003
Republican    4878
Other         2094
Name: count, dtype: int64

In [ ]:
df_leg['3_parties'].value_counts().sum()

np.int64(11975)

**Use new column for a new groupby**

In [ ]:
n_by_state_3party = df_leg.groupby(["state", "3_parties"])["last_name"].count()

/tmp/ipython-input-42-2336607784.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  n_by_state_3party = df_leg.groupby(["state", "3_parties"])["last_name"].count()

In [ ]:
#This gives the output I was looking for!

n_by_state_3party.head(20)

state  3_parties
AK     Democrat        8
       Other           3
       Republican      5
AL     Democrat      145
       Other          22
       Republican     39
AR     Democrat       94
       Other           6
       Republican     17
AS     Democrat        2
       Other           0
       Republican      0
AZ     Democrat       24
       Other           1
       Republican     23
CA     Democrat      167
       Other           8
       Republican    186
CO     Democrat       38
       Other           3
Name: last_name, dtype: int64

**View of the df whith a groupbby applied**

In [ ]:
#Defining 'by_state' which is our df grouped by state

by_state = df_leg.groupby("state")

/tmp/ipython-input-49-2122367150.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  by_state = df_leg.groupby("state")

In [ ]:
print(by_state)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7c001b124d90>

In [ ]:
#use this code to just show Pennsylvannia

by_state.get_group("PA")

,last_name,first_name,birthday,gender,type,state,party,3_parties
4,Clymer,George,1739-03-16,M,rep,PA,NaN,Other
19,Maclay,William,1737-07-20,M,sen,PA,Anti-Administration,Other
21,Morris,Robert,1734-01-20,M,sen,PA,Pro-Administration,Other
27,Wynkoop,Henry,1737-03-02,M,rep,PA,NaN,Other
38,Jacobs,Israel,1726-06-09,M,rep,PA,NaN,Other
...,...,...,...,...,...,...,...,...
11891,Brady,Robert,1945-04-07,M,rep,PA,Democrat,Democrat
11932,Shuster,Bill,1961-01-10,M,rep,PA,Republican,Republican
11945,Rothfus,Keith,1962-04-25,M,rep,PA,Republican,Republican
11959,Costello,Ryan,1976-09-07,M,rep,PA,Republican,Republican
11973,Marino,Tom,1952-08-15,M,rep,PA,Republican,Republican

**Another way - using loc() - to show the df with just one value from a column**

In [ ]:
#which is kind of the same as this

df_leg.loc[df_leg["state"] == "PA"]

,last_name,first_name,birthday,gender,type,state,party,3_parties
4,Clymer,George,1739-03-16,M,rep,PA,NaN,Other
19,Maclay,William,1737-07-20,M,sen,PA,Anti-Administration,Other
21,Morris,Robert,1734-01-20,M,sen,PA,Pro-Administration,Other
27,Wynkoop,Henry,1737-03-02,M,rep,PA,NaN,Other
38,Jacobs,Israel,1726-06-09,M,rep,PA,NaN,Other
...,...,...,...,...,...,...,...,...
11891,Brady,Robert,1945-04-07,M,rep,PA,Democrat,Democrat
11932,Shuster,Bill,1961-01-10,M,rep,PA,Republican,Republican
11945,Rothfus,Keith,1962-04-25,M,rep,PA,Republican,Republican
11959,Costello,Ryan,1976-09-07,M,rep,PA,Republican,Republican
11973,Marino,Tom,1952-08-15,M,rep,PA,Republican,Republican